from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
import re

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas

from smx_commerce.checkout import Order


@dataclass(frozen=True)
class ReceiptPdf:
    filename: str
    path: Path
    content: bytes


def _safe_filename(value: str) -> str:
    cleaned = re.sub(r"[^a-zA-Z0-9_.-]+", "-", value.strip())
    return cleaned.strip("-") or "receipt"


def generate_order_receipt_pdf(
    order: Order,
    *,
    receipts_dir: str | Path,
    brand_name: str = "smx-commerce",
    logo_path: str | Path | None = None,
) -> ReceiptPdf:
    receipts_path = Path(receipts_dir)
    receipts_path.mkdir(parents=True, exist_ok=True)

    receipt_id = f"receipt-{_safe_filename(order.public_id)}"
    filename = f"{receipt_id}.pdf"
    pdf_path = receipts_path / filename

    issued_at = datetime.now(timezone.utc)

    pdf = canvas.Canvas(str(pdf_path), pagesize=A4)
    width, height = A4

    left = 22 * mm
    top = height - 22 * mm
    y = top

    logo_file = Path(logo_path) if logo_path else None

    if logo_file and logo_file.exists():
        try:
            pdf.drawImage(
                str(logo_file),
                left,
                y - 20 * mm,
                width=38 * mm,
                height=18 * mm,
                preserveAspectRatio=True,
                mask="auto",
            )
        except Exception:
            pass

    pdf.setFont("Helvetica-Bold", 18)
    pdf.drawRightString(width - left, y, "Payment Receipt")

    y -= 12 * mm
    pdf.setFont("Helvetica", 10)
    pdf.setFillColor(colors.HexColor("#555555"))
    pdf.drawRightString(width - left, y, brand_name)

    y -= 18 * mm
    pdf.setFillColor(colors.black)
    pdf.setFont("Helvetica-Bold", 11)
    pdf.drawString(left, y, "Receipt details")

    y -= 8 * mm
    pdf.setFont("Helvetica", 10)

    details = [
        ("Receipt ID", receipt_id),
        ("Order ID", order.public_id),
        ("Issued at", issued_at.strftime("%Y-%m-%d %H:%M UTC")),
        ("Payment provider", order.payment_provider),
        ("Payment reference", order.payment_reference or ""),
        ("Status", order.status.value),
    ]

    for label, value in details:
        pdf.setFont("Helvetica-Bold", 9)
        pdf.drawString(left, y, f"{label}:")
        pdf.setFont("Helvetica", 9)
        pdf.drawString(left + 42 * mm, y, str(value))
        y -= 6 * mm

    y -= 8 * mm
    pdf.setFont("Helvetica-Bold", 11)
    pdf.drawString(left, y, "Buyer")

    y -= 8 * mm
    pdf.setFont("Helvetica", 10)

    buyer_details = [
        ("Name", order.buyer.full_name),
        ("Email", order.buyer.email),
        ("Phone", order.buyer.phone or ""),
        ("Company", order.buyer.company or ""),
    ]

    for label, value in buyer_details:
        if not value:
            continue
        pdf.setFont("Helvetica-Bold", 9)
        pdf.drawString(left, y, f"{label}:")
        pdf.setFont("Helvetica", 9)
        pdf.drawString(left + 42 * mm, y, str(value))
        y -= 6 * mm

    y -= 8 * mm
    pdf.setFont("Helvetica-Bold", 11)
    pdf.drawString(left, y, "Purchase")

    y -= 10 * mm

    table_top = y
    pdf.setStrokeColor(colors.HexColor("#d0d5dd"))
    pdf.setFillColor(colors.HexColor("#f2f4f7"))
    pdf.rect(left, table_top - 8 * mm, width - (2 * left), 8 * mm, fill=True, stroke=True)

    pdf.setFillColor(colors.black)
    pdf.setFont("Helvetica-Bold", 9)
    pdf.drawString(left + 3 * mm, table_top - 5.5 * mm, "Item")
    pdf.drawString(left + 90 * mm, table_top - 5.5 * mm, "Price option")
    pdf.drawRightString(width - left - 3 * mm, table_top - 5.5 * mm, "Amount")

    y = table_top - 16 * mm
    pdf.setFont("Helvetica", 9)
    pdf.drawString(left + 3 * mm, y, order.product_slug)
    pdf.drawString(left + 90 * mm, y, order.price_code)
    pdf.drawRightString(
        width - left - 3 * mm,
        y,
        f"{order.amount.currency.upper()} {order.amount.major():.2f}",
    )

    y -= 12 * mm
    pdf.setStrokeColor(colors.HexColor("#d0d5dd"))
    pdf.line(left, y, width - left, y)

    y -= 9 * mm
    pdf.setFont("Helvetica-Bold", 11)
    pdf.drawRightString(
        width - left - 3 * mm,
        y,
        f"Total paid: {order.amount.currency.upper()} {order.amount.major():.2f}",
    )

    footer_y = 24 * mm
    pdf.setFont("Helvetica", 8)
    pdf.setFillColor(colors.HexColor("#667085"))
    pdf.drawString(left, footer_y, "This receipt confirms that payment was received successfully.")
    pdf.drawString(left, footer_y - 5 * mm, f"Generated by {brand_name}.")

    pdf.showPage()
    pdf.save()

    return ReceiptPdf(
        filename=filename,
        path=pdf_path,
        content=pdf_path.read_bytes(),
    )